### ISSUE TITLE
Does the model not converge?

### ISSUE THREAD

**Issue by 15517965908** [icpm/super-resolution#6]

**Comment by icpm** [comment]
Could you specify which model is not converging?

**Comment by 15517965908** [comment]
![edsr](https://user-images.githubusercontent.com/23006154/48670631-7e638900-eb55-11e8-9b39-bb413b9490e3.png)

PSNR found negative values

**Comment by 15517965908** [comment]
![image](https://user-images.githubusercontent.com/23006154/48671261-634a4680-eb60-11e8-89d1-ea7c8f37f8c6.png)
DBPN

**Comment by 15517965908** [comment]
These models are all problematic. Can you correct them?

**Comment by tsaiting** [comment]
maybe your file path is wrong

**Comment by icpm** [comment]
`FSRCNN` works fine at my end and `DBPN` does converge but it's just SLOW.
