### ISSUE TITLE
problem with super_resolve.py

### ISSUE THREAD

**Issue by micklexqg** [icpm/super-resolution#8]
Hi, thanks for your work. I tried it with  'srcnn' and get a trained model.
but when i  am a little  confused with the result when applying the model with super_resolve.py .
input (default in super_resolve.py):
![image](https://user-images.githubusercontent.com/13776012/49002167-c9a31a80-f199-11e8-963c-bce7355f4ccc.png)
output:
![image](https://user-images.githubusercontent.com/13776012/49002199-e7707f80-f199-11e8-9e01-0c5a242a0fcf.png)
all parameters are set default, such as batchsize=1. why is it so?

**Comment by icpm** [comment]
I don't know the exact reason. However, I guess the possible cause is that I convert the image to `YCbCr` format and only feed `Y` channel as the input to the network. I'm working on changing the pre-processing so that the input will be RGB instead.

**Comment by icpm** [comment]
It seems like RGB configuration cannot preserve the color.

**Comment by icpm** [comment]
problem fixed

**Comment by NagasaiBharat** [comment]
@icpm @micklexqg   I am also getting the same problem ,i.e not getting the output in RGB. How can I fix it?

**Comment by illust** [comment]
> @icpm @micklexqg I am also getting the same problem ,i.e not getting the output in RGB. How can I fix it?

Hello, have you solved this problem?
