### ISSUE TITLE
confirm SRCNN

### ISSUE THREAD

**Issue by micklexqg** [icpm/super-resolution#9]
Hi, I am running your code. but I am a little puzzled about the SRCNN.
generally, the size of input is same as that of output as shown:
![image](https://user-images.githubusercontent.com/13776012/49585155-954d0c80-f998-11e8-9dcb-c1af80dadaaf.png)
but i do not find upsampling the resized or cropped batch.
does the srcnn lack pre-processing?

**Comment by icpm** [comment]
Hi, this graph is misleading but the code should be correct.

**Comment by icpm** [comment]
fixed the second `1x1` filters in SRCNN.
Thanks!

**Comment by micklexqg** [comment]
thanks for reply, I think  that it is right with the srcnn model, but lack two resize operation to produce training data and labels. it is just ok to add this preprocess.

**Comment by soapisnotfat** [comment]
Yeah, I intentionally delete the resize operations from the original implementation for fitting my unified dataset.
